name: CI Test for Local VM
on:
  push:
    branches:
      - feature-ci-local
#    braches와 함께 사용 불가능 / 특정 브랜치 무시
#    branches-ignore:
#      - main
#      - develop
    paths-ignore:
      - 'manifest/**' # 특정 디렉토리 무시

jobs:
  ci:
    environment: local-ci-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: add application.properties
        run: |
          echo "${{ secrets.APP_PROP }}" >> src/main/resources/application.properties

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test

      - name: Naming jar file
        run: mv ./build/libs/project2-team2-0.0.1-SNAPSHOT.jar ./build/libs/app.jar
        # @TODO regex

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        env:
          REPOSITORY: project2
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}:latest